apiVersion: apps/v1
kind: Deployment
metadata:
  name: okv2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: okv2
  template:
    metadata:
      labels:
        name: okv2
    spec:
      restartPolicy: Always
      containers:
        - name: okv2
          image: okv2/v2-repo
          ports:
            - containerPort: 23456
            
