apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ku
spec:
  replicas: 1
  selector:
    matchLabels:
      name: v2ku
  template:
    metadata:
      labels:
        name: v2ku
    spec:
      restartPolicy: Always
      containers:
        - name: okv2
          image: okv2/v2-repo
          ports:
            - containerPort: 23456
            
---
apiVersion: v1
kind: Service
metadata:
  name: v2kuurl
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "v2kuurl"
    port: 23456
  selector:
    name: v2kuurl
